// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR6-pUGPKwUW1XNXiXUyHEBvQOdMXTZGw',
    appId: '1:426389100522:web:9d34998188444c8e654493',
    messagingSenderId: '426389100522',
    projectId: 'chatappnti',
    authDomain: 'chatappnti.firebaseapp.com',
    storageBucket: 'chatappnti.firebasestorage.app',
    measurementId: 'G-0ZH1JTWQFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbaqYspAzYdMWwcW0ldPSorGhpaTVF-YY',
    appId: '1:426389100522:android:819e1e8d0ccbbfba654493',
    messagingSenderId: '426389100522',
    projectId: 'chatappnti',
    storageBucket: 'chatappnti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCky4cJm-pZ7twLckJdH1QF1q3HlvWlIG8',
    appId: '1:426389100522:ios:ba6c2a4beceea52a654493',
    messagingSenderId: '426389100522',
    projectId: 'chatappnti',
    storageBucket: 'chatappnti.firebasestorage.app',
    iosBundleId: 'com.example.ntiFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCky4cJm-pZ7twLckJdH1QF1q3HlvWlIG8',
    appId: '1:426389100522:ios:ba6c2a4beceea52a654493',
    messagingSenderId: '426389100522',
    projectId: 'chatappnti',
    storageBucket: 'chatappnti.firebasestorage.app',
    iosBundleId: 'com.example.ntiFinalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR6-pUGPKwUW1XNXiXUyHEBvQOdMXTZGw',
    appId: '1:426389100522:web:00cee3a2bc0cbf55654493',
    messagingSenderId: '426389100522',
    projectId: 'chatappnti',
    authDomain: 'chatappnti.firebaseapp.com',
    storageBucket: 'chatappnti.firebasestorage.app',
    measurementId: 'G-MWNYZZGW5F',
  );
}
